Re-add Mahout support
Adjust for all changes in Magpie 2.0 line and all changes
in testsuite.

diff --git a/magpie/job/magpie-job-mahout-clustersyntheticcontrol b/magpie/job/magpie-job-mahout-clustersyntheticcontrol
--- a/magpie/job/magpie-job-mahout-clustersyntheticcontrol
+++ b/magpie/job/magpie-job-mahout-clustersyntheticcontrol
@@ -22,61 +22,27 @@
 #  along with Magpie.  If not, see <http://www.gnu.org/licenses/>.
 #############################################################################
 
-# Various path constants that we want set
-#
-# This is used by scripts, don't edit this
+# This script is for running the mahout clustersyntheticcontrol sanity
+# test.  For the most part, it shouldn't be editted.  See job
+# submission files for configuration details.
 
-if [ "${HADOOP_SETUP}" == "yes" ]
+source ${MAGPIE_SCRIPTS_HOME}/magpie/lib/magpie-lib-paths
+
+# This is a job, no loading export files or libs except for minimal convenience ones
+
+export MAHOUT_WORK_DIR="${MAHOUT_LOCAL_SCRATCHSPACE_DIR}/mahout"
+
+if [ ! -d "${MAHOUT_WORK_DIR}" ]
 then
-    hadoopsetupscriptprefix="sbin"
-    hadoopcmdprefix="bin"
-    dfsadminscript="hdfs"
+    mkdir -p ${MAHOUT_WORK_DIR}
+    if [ $? -ne 0 ] ; then
+        echo "mkdir failed making ${MAHOUT_WORK_DIR}"
+        exit 1
+    fi
 fi
 
-if [ "${PIG_SETUP}" == "yes" ]
-then
-    pigcmdprefix="bin"
-fi
+command="${MAHOUT_HOME}/${mahoutexamplesprefix}/${mahoutcmdprefix}/cluster-syntheticcontrol.sh"
+echo "Running $command" >&2
+echo "1" | $command
 
-if [ "${MAHOUT_SETUP}" == "yes" ]
-then
-    mahoutexamplesprefix="examples"
-    mahoutcmdprefix="bin"
-fi
-
-if [ "${HBASE_SETUP}" == "yes" ]
-then
-    hbasesetupscriptprefix="bin"
-    hbasecmdprefix="bin"
-fi
-
-if [ "${PHOENIX_SETUP}" == "yes" ]
-then
-    phoenixcmdprefix="bin"
-fi
-
-if [ "${SPARK_SETUP}" == "yes" ]
-then
-    sparksetupscriptprefix="sbin"
-    sparkcmdprefix="bin"
-fi
-
-if [ "${KAFKA_SETUP}" == "yes" ]
-then
-    kafkacmdprefix="bin"
-fi
-
-if [ "${ZEPPELIN_SETUP}" == "yes" ]
-then
-    zeppelincmdprefix="bin"
-fi
-
-if [ "${STORM_SETUP}" == "yes" ]
-then
-    stormcmdprefix="bin"
-fi
-
-if [ "${ZOOKEEPER_SETUP}" == "yes" ]
-then
-    zookeepercmdprefix="bin"
-fi
+exit 0
